.TH MANAGELOGS 8 "Jan 2010" "managelogs" "managelogs"
.SH NAME
managelogs \- Piped logging program to rotate/purge Apache logs
.SH "SYNOPSIS"
.B managelogs
.RI " [ " options1 " ] " <base-path1> " [[ " options2 " ] " <base-path2> " ...]"
.SH "DESCRIPTION"
.PP
managelogs is a log processing program to be used in conjunction with Apache's
piped logfile feature. It automatically rotates and purges log files based
on a set of user-defined options.
.PP
Other features include :
.IP
- Rotation on a file size limit or time delay
.br
- Rotation on an external signal
.br
- Can run an external command in background each time a rotation occurs
.br
- Purge log files based on a combination of global size limit, number of log
files, and time delay
.br
- Integrated on-the-fly compression,
.br
- Maintains symbolic links on log files (active and/or backup),
.br
- Can change its uid/gid to run as a given (non-root) user/group,
.br
- Ensures that rotations occur on line boundaries,
.br
- Maintains its state across stop/start/restart operations
.PP
A managelogs process continuously reads data from its standard input and
sends it to its
.I log manager(s).
A log manager should be considered as an output channel. Each log 
manager is defined
on the command line by a set of options followed by a path named
.I base path
, as this path is used as the base every subsequent file names are computed
from. Each set of '[ \fIoptions\fR ] \fI<base-path>\fR' arguments defines a
log manager.
.PP
There is no limit to the number of log managers a
managelogs process can handle. They all receive a copy of the data read from
the process' standard input and each one processes this data according to its
configuration.
.PP
Note: In most cases, and especially
during your first steps with managelogs, you will define only one log
manager, making no difference between the log manager and the managelogs process
it belongs to.
.PP
A log manager manages an
.I active
log file (the file it is currently writing into) and a set of
.I backup
log files.
.I Backup
log files are previous active log files which have been closed during a
.I rotation.
Every time the global limits
are exceeded, a
.I purge
operation takes place and the oldest backup file is deleted.
.PP
Each log manager also maintains a
.I status file
which, among other information, contains the paths of the active and backup log
files. Thanks to this file, a managelogs process can be stopped and restarted
without loosing its state. When a managelogs process is restarted, each log
manager recovers the state it was in when the process was previously stopped.
.PP
Note : unlike other log management programs like
rotatelogs, (re)starting the Apache server does not cause its managelogs
processes to switch to a new log file. The only way to force a file rotation
from the 'outside' is to send a SIGUSR1 signal to the managelogs process
(see SIGNALS).
.PP
Another difference with other log rotation programs is that different
processes cannot write to the same log file. A given
.I base path
must be privately owned and managed by only one log manager. If another program
writes to one of the files maintained by this log manager, the result is unpredictable.
The only exception to this rule is that backup log files can be deleted
(but not written to) at any time without disturbing the logic of the purge
engine.
.SH "OPTIONS"
.PP
---- Global options (these options apply to the whole managelogs process) :
.TP
.BR -h | --help
Display the list of available options and exit
.TP
.BR -V | --version
Display current version and exit
.TP
.BR -u | --user " " \fI<id>\fR
run with this user/group ID (usable only when the program is started
by \fIroot\fR)
.br
\fI<id>\fR = \fI<uid>[:<gid>]\fR, where \fI<uid>\fR and \fI<gid>\fR are 
user/group names or numeric ids.
.TP
.BR -I | --stats
Display internal statistics before exiting (used for troubleshooting, debugging,
or performance tests)
.TP
.BR -R | --refresh-only
Just refresh/purge log files and exit
.PP
---- Log manager options (apply to the next \fI<base-path>\fR only) :
.TP
.BR -v | --verbose
Increment debug level (can be set more than once).
.TP
.BR -d | --debug " " \fI<path>\fR
Write debug messages to \fI<path>\fR.
.br
Special values : 'stdout' and 'stderr' respectively correspond to
the process' standard output and standard error streams.
.br
Default : debug messages go to stderr.
.TP
.BR -c | --compress " " \fI<comp>[:<level>]\fR
Activate compression and append the corresponding suffix to the log file names.
.br
\fI<comp>\fR may be \fBgz\fR or \fBbz2\fR (this is also the value of the
suffix appended to the log file names).
.br
\fI<level>\fR is one of {1|2|3|4|5|6|7|8|9|best|fast}
.br
Default compression level: best
.TP
.BR -s | --size " " \fI<size>\fR
Sets the log file size at which rotation occurs.
.br
\fI<size>\fR is a numeric value
optionnally followed by a unit : \fBK\fR (Kilobytes), \fBM\fR (Megabytes), or
\fBG\fR (Gigabytes).
.br
Default: no limit
.br
Note that the size we set here is the size the file takes on disk. If compression
is turned on, the limit is checked against the compressed size.
.TP
.BR -r|--rotate-delay " " \fI<delay>\fR
Sets the maximum delay between the creation of a new log file and the next
rotation.
.br
\fI<delay>\fR is a suite of patterns in the form '[0-9]+[dhm]' (d=days, h=hours,
m=minutes)
.br
Example : 1d12h = 1 day and 12 hours (same as '36h')\n\
.TP
.BR -p|--purge-delay \fI<delay>\fR
Removes backup log files older than \fI<delay>\fR
.br
Argument: same format as for '--rotate-delay'
.TP
.BR -S | --global-size " " \fI<size>\fR
Sets the maximum size that the managed log files (active + backup) can take on
disk. As soon as this size is exceeded, a purge occurs (the oldest backup file
is removed).
.br
Argument: same format as for '--size'. If this option is set and the '--size'
option is not, the individual file limit is implicitely set to 1/2 of
the global limit (so that the directory always contains at least one backup
file).
.br
Default : no global limit
.TP
.BR -m | --mode " " \fI<mode>\fR
File permissions to apply to newly-created log files.
.br
\fI<mode>\fR is a numeric octal Unix-style file permission (see chmod(1) for more).
.br
Default mode: 644
.TP
.BR -k | --keep " " \fI<n>\fR
Keep only \fI<n>\fR log files (the active one + \fI<n-1>\fR backups). This
option is an alternative to the '--global-size' option, but can also be
used in conjunction, especially if you send signals to trigger rotations
before the size limit is reached. 
.TP
.BR -l | --link
Maintain a link file (named \fI<base-path>\fR) to the active log file.
.TP
.BR -L | --backup-links
Also maintain links to the backup log files (backup links are named
\fI<base-path>.{001,002,...}\fR, most recent first)
.TP
.BR -H | --hardlink
Create hard links instead of symbolic links.
.TP
.BR -e | --ignore-eol
By default, managelogs ensures that log file rotation occurs on line boundaries,
so that every log files contain entire lines. This option disables this
buffering mechanism.
.TP
.BR -C | --rotate-cmd " " \fI<cmd>\fR
Run this command in background each time a rotation occurs.
.br
See 'ROTATE COMMAND' below for more info on this option
.TP
.BR -x | --enospc-abort
Abort on 'file system full' errors.
.br
The default is to ignore such errors when trying to write data to a log file,so
that the underlying service (typically Apache) is kept running as long as
possible. The drawback is that, when it happens, data that cannot be written is
silently discarded.
.SH "FILES"
Each log manager maintains its own set of files. The files are named after the
log manager's base path. They all reside in the same directory (the directory
part of the base path). This directory must exist before managelogs is started.
It must also be writable by the user managelogs is running as.
.PP
Here are the files that a log manager creates and maintains :
.TP
<base-path>.pid
This file is present when a process is currently managing this base path. It
contains
the pid of the managelogs process. This is the file to read to know who to send
signals to. When the process exits, the pid file is removed.
.TP
<base-path>.status
The status file. As described above, this file allows a log manager to recover
its previous state at start time. This way, the memory of active and backup
files is kept.
.TP
<base-path>._\fI<xxxxxxxx>\fR[.gz|.bz2]
A log file. The \fI<xxxxxxxx>\fR part of the name is a unique identifier
computed
by the log manager when the file is created. When several log files are present,
their alphabetical order always corresponds to their creation time chronological
order. So, when you list a directory in
alphabetical order, the oldest backup
log file comes first, and the active log
file comes last. And a command like 'cat <base-path>._*' displays the
whole log data in chronological order.
.br
When compression is turned on, the log manager automatically appends the
compression type to the file name.
.TP
<base-path>
If the '--link' option is set for this log manager, it maintains a link
from <base-path> to the active log file. By default, it is a symbolic link,
but the '--hardlink' option allows to use hard links instead.
.TP
<base-path>.{001,002,...}
These are also links, but to the backup log files. They are created and
maintained only if the '--backup-links' option was set. The files are numbered
in reverse chronological order : <base-path>.001 is the most recent backup,
<base-path>.002 is the previous one...
.SH "SIGNALS"
.TP
.B SIGUSR1
This signal triggers an immediate rotation on every log managers attached to
the process. Note that the rotation can cause the global conditions
to be exceeded. In this case, a purge will follow. 
.TP
.B SIGUSR2
This signal causes every log managers to flush to disk the data they may
have in memory. This is especially useful for compressed streams, as compressed
files
cannot be read before such a flush operation is executed. This is due to the
fact that a compressed file must contain a trailer block to be valid. As long
as the compression engine processes the data, this trailer block is not
written and, if you try to read the compressed data from the file, it is
considered as invalid. When you send a SIGUSR2 to the process, the compression
engine flushes the data it currently has in memory, writes the corresponding
trailer data to the file, and starts a new block. Then, you can uncompress
the data from the compressed file. Note that this flush operation adds about
16 bytes to the log file, so it shouldn't be done too often.
.SH "ROTATE COMMAND"
Every time managelogs decides to switch to a new log file, whatever reason it
may have for this, an external command can be executed. This is what we call
.I rotate command.
This command is set via the --rotate-cmd option on the managelogs command line.
It is a shell command line, which
can contain arguments, separated by spaces or tabs. If the command contains
arguments, it must be enclosed between quotes, so that it is seen as a single
managelogs argument.
.PP
managelogs runs the command in background, ignoring its return code. Once
launched, the subprocess is totally forgotten by the managelogs process. So,
there is no limit to the time it may take, as it does not suspend managelogs
execution.
.PP
Before launching the rotate command, managelogs sets several environment
variables that can be used, either in the command string (prefixed with a $
sign), or from within the script or program run by the command:
.TP
.B LOGMANAGER_FILE_PATH
The path to the log file managelogs just closed. In a statistics gathering
scenario, the data to integrate will be read from this file.
.TP
.B LOGMANAGER_BASE_PATH
This is the
.I base path
associated with this log manager.
.TP
.B LOGMANAGER_ROOT_DIR
This is the directory part of the
.I base path
.TP
.B LOGMANAGER_COMPRESSION
This is the compression type used to write to the log file. If compression
is off, contains an empty string.
.TP
.B LOGMANAGER_VERSION
The version of the log manager library.
.TP
.B LOGMANAGER_TIME
The current time in Unix numeric format (number of seconds since 01/Jan/1970).
.PP
Note : During its execution, the rotate command is allowed to delete the
file pointed by $LOGMANAGER_FILE_PATH. You may do it, for instance, if you just
want some statistics without keeping the detailed logs, or if you use the rotate
command to transfer the log file to another location/server.
.SH "EXAMPLES"
.PP
Say we want to keep the last 3 Mbytes of access_log data in <apache-dir>/logs,
each log file will take at most 1 Mbyte, and we want to maintain symbolic
links to the active and backup log files.
.PP
The corresponding configuration line looks like :
.PP
CustomLog "| /usr/bin/managelogs --size 1M --global-size 3M --link --backup-links <apache_dir>/logs/access_log" combined
.PP
Here is a typical list of files present in the <apache-dir>/logs directory with
such a configuration :
.nf
# ls -l $apache_dir/logs/access_log*
\...
lrwxrwxrwx 1 root root      20 Mar 17 15:16 access_log -> access_log._49BFB0A2
lrwxrwxrwx 1 root root      20 Mar 17 15:16 access_log.001 -> access_log._49BF8366
lrwxrwxrwx 1 root root      20 Mar 17 15:16 access_log.002 -> access_log._49BF2522
-rw-r--r-- 1 root root 1048564 Mar  5 12:34 access_log._49BF2522
-rw-r--r-- 1 root root 1048543 Mar 17 15:16 access_log._49BF8366
-rw-r--r-- 1 root root  483328 Mar 19 07:05 access_log._49BFB0A2
-rw-r--r-- 1 root root       6 Feb 22 08:30 access_log.pid
-rw-r--r-- 1 root root     321 Mar 17 15:16 access_log.status
.fi
.TP
In this list you can see (in alphabetical order) :
- The symbolic link to the active log file
.br
- The 2 symbolic links to the 2 backup log files
.br
- The 2 backup log files (in chronological order)
.br
- The active log file
.br
- The pid file
.br
- The status file
.PP
Now, something more complex : we want to keep 3 Mbytes of uncompressed log
data
to be used by the 1st-level support team, as in the previous example, and we
also need to archive a bigger amount of data for 2nd-level analysis,
security, compliance, or any other need. This archived data will be compressed,
as it allows to save a lot of space (about 95 %).
.PP
The corresponding directive looks like :
.PP
CustomLog "| /usr/bin/managelogs --size 1M --global-size 3M --link --backup-links <apache_dir>/logs/access_log --size 100M --global-size 1G --compression bz2:best /archives/logs/access_log" combined
.PP
With such a configuration, the files in the <apache-dir>/logs directory will
be the same as in the previous example, but managelogs will also maintain the
most recent 1 Gbytes of compressed access log data in /archives/logs (in
chunks of 100 Mbytes). This way, we have two levels of access to the log
data : the most recent data is easily accessible and, when we need to examine
something older, it is less easy, but the retention size is much larger.
.PP
Now, if we want to force an immediate rotation of these log files, whatever
reason we may have for this, the command to use is :
.PP
kill -USR1 `cat <apache-dir>/logs/access_log.pid`
.PP
Note that we could also have used '/archives/logs/access_log.pid', as both pid
files contain the same. This signal will trigger a rotation in both directories.
.PP
Here is a typical example of using a rotate command : the options below cause
the log data to be integrated into an AWStats database each time a rotation
occurs. We also ensure that a rotation happens at least every day :
.PP
CustomLog "| /usr/bin/managelogs --size 100k --global-size 1M --rotate-delay 1d --rotate-cmd 'perl <awstat-dir>/awstats.pl -config=<mysite> -update -LogFile=$LOGMANAGER_FILE_PATH' <apache_dir>/logs/access_log" combined
.PP
In order to ensure that statistics are integrated at least once per day, we
could have replaced the '--rotate-delay' option with the following cron job,
executed every night :
.PP
0 0 * * * kill -USR1 `cat <apache_dir>/logs/access_log.pid`
.SH "SEE ALSO"
.PP
The managelogs web site : http://managelogs.tekwire.net
.SH "AUTHOR"
.PP
Francois Laupretre <francois@tekwire.net>
.SH "LICENSE"
.PP
Apache license, Version 2.0 <http://www.apache.org/licenses/>
.SH BUGS
.PP
Please send bug reports to <managelogs-bugs@tekwire.net>
