.TH MANAGELOGS 8 "March 2009" "managelogs" "managelogs"
.SH NAME
managelogs \- Piped logging program to rotate/purge Apache logs
.SH "SYNOPSIS"
.B managelogs
.RI " [ " options1 " ] " <base-path1> " [[ " options2 " ] " <base-path2> " ...]"
.SH "DESCRIPTION"
.PP
managelogs is a log processing program to be used in conjunction with Apache's
piped logfile feature. It automatically rotates and purges log files based
on a set of user-defined options.

The primary purpose is to solve the 'log file system full' issue in a
way different from the quite-unreliable cron-based solutions one
typically uses to solve it. The approach is different, here, because the purge
is not delegated to an external program. This way, even if the file system is
limited in free space, the size limits you define will never be exceeded, even
temporarily.
.PP
Main features :
.IP
- File rotation based on individual file size or on a signal,
.br
- File purge based on a global size limit, a maximum number of files,
or a combination of both,
.br
- Optional on-the-fly compression,
.br
- Can maintain symbolic links on log files (active and backup),
.br
- Can switch to a given (non-root) uid/gid,
.br
- Ensures that rotations occur on line boundaries,
.br
- Maintains its state across stop/starts/restarts
.PP
A managelogs process continuously reads data from its standard input and
sends it to its
.I log manager(s).
Log managers should be considered as independant output channels. Each log 
manager is defined
on the command line by a set of options followed by a path we call the
.I base path
, as this path is used as the base every file names are computed from. Each set
of '[ \fIoptions\fR ] \fI<base-path>\fR' arguments on the command line
defines a log manager.
.PP
There is no limit to the number of log managers a
process can handle. They all receive a copy of the data read from
the process' standard input and each one processes it according to its
configuration.
.PP
Note: In most cases, and especially
during your first steps with managelogs, you will define only one log
manager and you won't make the difference between it and the process
it belongs to.
.PP
A log manager manages an
.I active
log file (the file it is currently writing into) and a set of
.I backup
log files.
.I Backup
files are previous log files which have been closed during a file
.I rotation.
Every time the global limits
are exceeded, a
.I purge
occurs, meaning that the oldest backup file is deleted.
.PP
Each log manager also maintains a
.I status file
which, among other information, contains the names of the active and backup log
files. Thanks to this file, managelogs processes can be stopped and restarted
without loosing their state. So, when a process is started, each log manager
recovers the state it was in when the previous process was stopped. It means,
among others, that it will reopen the log file it was writing into when it was
stopped.
As a consequence, note that, unlike other log managemenent programs like
rotatelogs, (re)starting the Apache server does not cause managelogs to
switch to a new log file. In order to force a file rotation, you must send
a SIGUSR1 signal to the process (see SIGNALS).

Another difference with other log management programs is that you cannot
share an active log file between several processes. In the managelogs world,
each
.I base path
is privately owned and managed by only one log manager. If another program
writes to the active log file, the result is undefined. The rule is less strict
for backup log files : writing into them is forbidden, but they can be deleted
by an external program (before actually performing a purge, the log manager
checks the presence of each backup file and recomputes the global size).
.SH "OPTIONS"
.PP
---- Global options (apply to the process) :
.TP
.BR -h | --help
Display the list of available options
.TP
.BR -u | --user " " \fI<id>\fR
run with this user ID (possible only when the program is started by the root 
user).
.br
\fI<id>\fR = \fI<uid>[:<gid>]\fR, where \fI<uid>\fR and \fI<gid>\fR are 
user/group names or numeric ids.
.TP
.BR -V | --version
Print version and exit.
.TP
.BR -I | --stats
Display internal statistics before exiting (used for troubleshooting, debugging, or
performance tests)
.TP
.BR -R | --refresh-only
Just refresh/purge files and exit
.PP
---- Log manager options (apply to the following \fI<base-path>\fR only) :
.TP
.BR -v | --verbose
Increment debug level (can be set more than once).
.TP
.BR -d | --debug " " \fI<path>\fR
Write debug messages to \fI<path>\fR.
.br
\fI<path>\fR can be 'stdout' or 'stderr'.
.br
Default : stderr.
.TP
.BR -c | --compress " " \fI<comp>[:<level>]\fR
Activate compression and append the corresponding suffix to the log file names.
.br
\fI<comp>\fR is \fBgz\fR or \fBbz2\fR (this is also the value of the appended
suffix).
.br
\fI<level>\fR is one of {1|2|3|4|5|6|7|8|9|best|fast}
.br
The default compression level depends on the compression engine.
.br
If this option is not present, the output flow is not compressed.
.TP
.BR -s | --size " " \fI<size>\fR
Sets the log file size at which rotation occurs.
.br
\fI<size>\fR is a numeric value
optionnally followed by 'k|K' (Kilobytes), 'm|M' (Megabytes), or 'g|G'
(Gigabytes).
.br
Default: no size limit
.TP
.BR -S | --global-size " " \fI<size>\fR
Sets the maximum size that the managed log files (active + backup) can take .
When this size is reached, a purge occurs (the oldest backup file is removed).
.br
Argument: same format as '--size'. If this argument is set and the '--size'
argument is not, the individual file limit is implicitely set to a value of
one half of the global size (so that the directory always contains one backup
file).
.br
Default : no global size limit.
.TP
.BR -m | --mode " " \fI<mode>\fR
File permissions to apply to newly-created log files.
.br
\fI<mode>\fR is a numeric Unix-style file permission (see chmod for more).
.br
Default mode: 644
.TP
.BR -k | --keep " " \fI<n>\fR
Only keep \fI<n>\fR log files (the active one + \fI<n-1>\fR backups). This
option is an alternative to the '--global-size' option, but it can also be
used in conjunction, especially if you use signals to trigger some rotations
before the sizes reach their limits. When this argument is set along with a
global size limit, the first limit to be reached triggers the purge operation. 
.TP
.BR -l | --link
Maintain a link file (named \fI<base-path>\fR) to the active log file. The '-H'
option allows to choose between hard or symbolic links.
.TP
.BR -L | --backup-links
Also maintain links to the backup log files (backup links are named
\fI<base-path>.{1,2,...}\fR, most recent first)
.TP
.BR -H | --hardlink
Create hard links instead of symbolic links.
.TP
.BR -e | --ignore-eol
By default, managelogs ensures that log file rotation occurs on line boundaries,
so that log files contain entire lines. This option disables this mechanism.
.SH "FILES"
Each log manager maintains its own set of files. The files are named after the
manager's base path. They all lie in the same directory (the directory part of
the base path).
.PP
Here are the files that a log manager may create and maintain :
.TP
<base-path>.pid
This file is present when a process is currently managing this path. It contains
the pid of the managelogs process. This is the file to read if you want to send
signals. When the process exits, the pid file is removed.
.TP
<base-path>.status
The status file. As described above, this file allows a log manager to recover
its previous state at start time. This way, the memory of active and backup
files is kept.
.TP
<base-path>._\fI<xxxxxxxx>\fR.log[.gz|.bz2]
A log file. The \fI<xxxxxxxx>\fR part of the name is a unique identifier
computed
by the log manager when the file is created. When several log files are present,
their alphabetical order always corresponds to their creation time chronological
order. So, when you list a directory in
alphabetical order (ls -l), the oldest backup
log file comes first, and the active log
file comes last. And a command like 'cat <base-path>._*.log' displays the
whole log data in chronological order.
.br
When compression is turned on, the log manager automatically appends the
compression type to the file name.
.TP
<base-path>
If the '--link' option is set for this log manager, it maintains a link
from <base-path> to the active log file. By default, it is a symbolic link,
but the '--hardlink' option allows to use hard links.
.TP
<base-path>.{1,2,...}
These are also links, but to the backup log files. They are created and
maintained only if the '--backup-links' option was set. The files are numbered
in reverse chhronological order : <base-path>.1 is the most recent backup,
<base-path>.2 is the previous one...
.SH "SIGNALS"
.TP
SIGUSR1
This signal triggers an immediate rotation on every log managers attached to
the managelogs process. Note that, if the '--keep' option is set, and if the
maximum number of log files is exceeded, a purge will occur. 
.TP
SIGUSR2
This signal causes every log managers to flush to disk the data they may
have in memory. This is useful only for compressed streams, as compressed files
cannot be read before such a flush operation is done. This is due to the fact
that a compressed file must contain a trailer block to be valid. As long
as the compression engine processes the data, this trailer block is not
written and, if you try to read the compressed data from the file, it is
considered as invalid. When you send a SIGUSR2 to the process, the compression
engine flushes the data it currently has in memory, writes the corresponding
trailer data to the file, and starts a new block. Then, you can uncompress
the data from the compreessed file. Note that this flush operation adds about
16 bytes to the log file, so it shouldn't be done too often.
.SH "EXAMPLES"
.PP
Say we want to keep the last 3 Mbytes of access_log data in <apache-dir>/logs,
each log file will take at most 1 Mbytes, and we want to maintain a symbolic
link to the active and backup log files.
.PP
The corresponding configuration line looks like :
.PP
CustomLog "| <apache_dir>/bin/managelogs --size 1M --global-size 3M --link --backup-links <apache_dir>/logs/access_log" combined
.PP
Here is a typical list of files present in the <apache-dir>/logs directory with
such a configuration :
.nf
# ls -l $apache_dir/logs/access_log*
\...
lrwxrwxrwx 1 root root      20 Mar 17 15:16 access_log -> access_log._49BFB0A2
lrwxrwxrwx 1 root root      20 Mar 17 15:16 access_log.1 -> access_log._49BF8366
lrwxrwxrwx 1 root root      20 Mar 17 15:16 access_log.2 -> access_log._49BF2522
-rw-r--r-- 1 root root 1048564 Mar  5 12:34 access_log._49BF2522
-rw-r--r-- 1 root root 1048543 Mar 17 15:16 access_log._49BF8366
-rw-r--r-- 1 root root  483328 Mar 19 07:05 access_log._49BFB0A2
-rw-r--r-- 1 root root       6 Feb 22 08:30 access_log.pid
-rw-r--r-- 1 root root     321 Mar 17 15:16 access_log.status
.fi
.TP
In this list you can see (in alphabetical order) :
- The symbolic link to the active log file
.br
- The 2 symbolic links to the 2 backup log files
.br
- The 2 backup log files (in chronological order)
.br
- The active log file
.br
- The pid file
.br
- The status file
.PP
Now, something more complex : we want to keep 3 Mbytes of uncompressed log
data
to be used by the 1st-level support team, as in the previous example, and we
also need to archive a bigger amount of data for 2nd-level analysis,
security, compliance, or any other need. This archived data will be compressed,
as it allows to save a lot of space (about 95 %).
.PP
The corresponding directive looks like :
.PP
CustomLog "| <apache_dir>/bin/managelogs --size 1M --global-size 3M --link --backup-links <apache_dir>/logs/access_log --size 100M --global-size 1G --compression bz2:best /archives/logs/access_log" combined
.PP
With such a configuration, the files in the <apache_dir>/logs directory will
be the same  as in the previous example, but it will also maintain the most
recent 1 Gbytes of compressed access_log data in /archives/logs (in
chunks of 100 Mbytes). This way, we have two levels of access to the log
data : the most recent data is easily accessible and, when we need to examine
something older, it is less easy, but the retention size is much bigger.
.PP
Now, if we want to force an immediate rotation of these log files, whatever
reason we may have for this, the command to use is :
.PP
kill -USR1 `cat <apache_dir>/logs/access_log.pid`
.PP
Note that we could also have used '/archives/logs/access_log.pid', as both pid
files contain the same. This signal will trigger a rotation in both directories.
.SH "SEE ALSO"
.PP
managelogs web site : http://managelogs.tekwire.net
.SH "LICENSE"
.PP
Apache license, Version 2.0 <http://www.apache.org/licenses/>
.SH BUGS
.PP
Please send bug reports to <managelogs-bugs@tekwire.net>
.SH "AUTHOR"
.PP
Francois Laupretre <francois@tekwire.net>
